-- test comment
CREATE WORKER "sink-node:9090" AT "sink-node:8080";
CREATE LOGICAL SOURCE endless(ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
       'ALL' as `SOURCE`.STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
       'CSV' as PARSER.`TYPE`,
       10000000 AS `SOURCE`.MAX_RUNTIME_MS,
       "sink-node:9090" AS `SOURCE`.`HOST`,
       'emit_rate 10' AS `SOURCE`.GENERATOR_RATE_CONFIG,
       1 AS `SOURCE`.SEED,
       'SEQUENCE UINT64 0 10000000 1' AS `SOURCE`.GENERATOR_SCHEMA);
CREATE SINK someSink(ENDLESS.TS UINT64) TYPE File SET('out.csv' as `SINK`.FILE_PATH, 'CSV' as `SINK`.INPUT_FORMAT, "sink-node:9090" AS `SINK`.`HOST`);
SHOW QUERIES;
SELECT TS FROM ENDLESS INTO SOMESINK SET ('distributed-query' AS `QUERY`.`ID`);

SHOW QUERIES WHERE id = 'distributed-query';
DROP QUERY WHERE id = 'distributed-query';

SHOW QUERIES;
